// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bio_pages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBioPage = `-- name: CreateBioPage :one
INSERT INTO bio_pages (workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url, is_published, created_at, updated_at, deleted_at
`

type CreateBioPageParams struct {
	WorkspaceID     uuid.UUID   `json:"workspace_id"`
	Slug            string      `json:"slug"`
	Title           string      `json:"title"`
	Bio             pgtype.Text `json:"bio"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
	ThemeID         pgtype.UUID `json:"theme_id"`
	CustomCss       pgtype.Text `json:"custom_css"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	OgImageUrl      pgtype.Text `json:"og_image_url"`
}

func (q *Queries) CreateBioPage(ctx context.Context, arg CreateBioPageParams) (BioPage, error) {
	row := q.db.QueryRow(ctx, createBioPage,
		arg.WorkspaceID,
		arg.Slug,
		arg.Title,
		arg.Bio,
		arg.AvatarUrl,
		arg.ThemeID,
		arg.CustomCss,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgImageUrl,
	)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarUrl,
		&i.ThemeID,
		&i.CustomCss,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBioPageByID = `-- name: GetBioPageByID :one
SELECT id, workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url, is_published, created_at, updated_at, deleted_at FROM bio_pages
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBioPageByID(ctx context.Context, id uuid.UUID) (BioPage, error) {
	row := q.db.QueryRow(ctx, getBioPageByID, id)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarUrl,
		&i.ThemeID,
		&i.CustomCss,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBioPageBySlug = `-- name: GetBioPageBySlug :one
SELECT id, workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url, is_published, created_at, updated_at, deleted_at FROM bio_pages
WHERE slug = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBioPageBySlug(ctx context.Context, slug string) (BioPage, error) {
	row := q.db.QueryRow(ctx, getBioPageBySlug, slug)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarUrl,
		&i.ThemeID,
		&i.CustomCss,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBioPagesForWorkspace = `-- name: ListBioPagesForWorkspace :many
SELECT id, workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url, is_published, created_at, updated_at, deleted_at FROM bio_pages
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListBioPagesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]BioPage, error) {
	rows, err := q.db.Query(ctx, listBioPagesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BioPage{}
	for rows.Next() {
		var i BioPage
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Slug,
			&i.Title,
			&i.Bio,
			&i.AvatarUrl,
			&i.ThemeID,
			&i.CustomCss,
			&i.MetaTitle,
			&i.MetaDescription,
			&i.OgImageUrl,
			&i.IsPublished,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBioPage = `-- name: UpdateBioPage :one
UPDATE bio_pages
SET
    slug = COALESCE($2, slug),
    title = COALESCE($3, title),
    bio = COALESCE($4, bio),
    avatar_url = COALESCE($5, avatar_url),
    theme_id = COALESCE($6, theme_id),
    custom_css = COALESCE($7, custom_css),
    meta_title = COALESCE($8, meta_title),
    meta_description = COALESCE($9, meta_description),
    og_image_url = COALESCE($10, og_image_url),
    is_published = COALESCE($11, is_published),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, slug, title, bio, avatar_url, theme_id, custom_css, meta_title, meta_description, og_image_url, is_published, created_at, updated_at, deleted_at
`

type UpdateBioPageParams struct {
	ID              uuid.UUID   `json:"id"`
	Slug            pgtype.Text `json:"slug"`
	Title           pgtype.Text `json:"title"`
	Bio             pgtype.Text `json:"bio"`
	AvatarUrl       pgtype.Text `json:"avatar_url"`
	ThemeID         pgtype.UUID `json:"theme_id"`
	CustomCss       pgtype.Text `json:"custom_css"`
	MetaTitle       pgtype.Text `json:"meta_title"`
	MetaDescription pgtype.Text `json:"meta_description"`
	OgImageUrl      pgtype.Text `json:"og_image_url"`
	IsPublished     pgtype.Bool `json:"is_published"`
}

func (q *Queries) UpdateBioPage(ctx context.Context, arg UpdateBioPageParams) (BioPage, error) {
	row := q.db.QueryRow(ctx, updateBioPage,
		arg.ID,
		arg.Slug,
		arg.Title,
		arg.Bio,
		arg.AvatarUrl,
		arg.ThemeID,
		arg.CustomCss,
		arg.MetaTitle,
		arg.MetaDescription,
		arg.OgImageUrl,
		arg.IsPublished,
	)
	var i BioPage
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Slug,
		&i.Title,
		&i.Bio,
		&i.AvatarUrl,
		&i.ThemeID,
		&i.CustomCss,
		&i.MetaTitle,
		&i.MetaDescription,
		&i.OgImageUrl,
		&i.IsPublished,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const softDeleteBioPage = `-- name: SoftDeleteBioPage :exec
UPDATE bio_pages
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBioPage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteBioPage, id)
	return err
}

const getBioPageCountForWorkspace = `-- name: GetBioPageCountForWorkspace :one
SELECT COUNT(*) AS count FROM bio_pages
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetBioPageCountForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getBioPageCountForWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

// ============================================================================
// Bio Page Links
// ============================================================================

const createBioPageLink = `-- name: CreateBioPageLink :one
INSERT INTO bio_page_links (bio_page_id, title, url, icon, position, is_visible, visible_from, visible_until)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, bio_page_id, title, url, icon, position, is_visible, visible_from, visible_until, click_count, created_at, updated_at
`

type CreateBioPageLinkParams struct {
	BioPageID    uuid.UUID          `json:"bio_page_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Icon         pgtype.Text        `json:"icon"`
	Position     int32              `json:"position"`
	IsVisible    bool               `json:"is_visible"`
	VisibleFrom  pgtype.Timestamptz `json:"visible_from"`
	VisibleUntil pgtype.Timestamptz `json:"visible_until"`
}

func (q *Queries) CreateBioPageLink(ctx context.Context, arg CreateBioPageLinkParams) (BioPageLink, error) {
	row := q.db.QueryRow(ctx, createBioPageLink,
		arg.BioPageID,
		arg.Title,
		arg.Url,
		arg.Icon,
		arg.Position,
		arg.IsVisible,
		arg.VisibleFrom,
		arg.VisibleUntil,
	)
	var i BioPageLink
	err := row.Scan(
		&i.ID,
		&i.BioPageID,
		&i.Title,
		&i.Url,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.VisibleFrom,
		&i.VisibleUntil,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBioPageLinkByID = `-- name: GetBioPageLinkByID :one
SELECT id, bio_page_id, title, url, icon, position, is_visible, visible_from, visible_until, click_count, created_at, updated_at FROM bio_page_links
WHERE id = $1
`

func (q *Queries) GetBioPageLinkByID(ctx context.Context, id uuid.UUID) (BioPageLink, error) {
	row := q.db.QueryRow(ctx, getBioPageLinkByID, id)
	var i BioPageLink
	err := row.Scan(
		&i.ID,
		&i.BioPageID,
		&i.Title,
		&i.Url,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.VisibleFrom,
		&i.VisibleUntil,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBioPageLinks = `-- name: ListBioPageLinks :many
SELECT id, bio_page_id, title, url, icon, position, is_visible, visible_from, visible_until, click_count, created_at, updated_at FROM bio_page_links
WHERE bio_page_id = $1
ORDER BY position ASC
`

func (q *Queries) ListBioPageLinks(ctx context.Context, bioPageID uuid.UUID) ([]BioPageLink, error) {
	rows, err := q.db.Query(ctx, listBioPageLinks, bioPageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BioPageLink{}
	for rows.Next() {
		var i BioPageLink
		if err := rows.Scan(
			&i.ID,
			&i.BioPageID,
			&i.Title,
			&i.Url,
			&i.Icon,
			&i.Position,
			&i.IsVisible,
			&i.VisibleFrom,
			&i.VisibleUntil,
			&i.ClickCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBioPageLink = `-- name: UpdateBioPageLink :one
UPDATE bio_page_links
SET
    title = COALESCE($2, title),
    url = COALESCE($3, url),
    icon = COALESCE($4, icon),
    is_visible = COALESCE($5, is_visible),
    visible_from = COALESCE($6, visible_from),
    visible_until = COALESCE($7, visible_until),
    updated_at = NOW()
WHERE id = $1
RETURNING id, bio_page_id, title, url, icon, position, is_visible, visible_from, visible_until, click_count, created_at, updated_at
`

type UpdateBioPageLinkParams struct {
	ID           uuid.UUID          `json:"id"`
	Title        pgtype.Text        `json:"title"`
	Url          pgtype.Text        `json:"url"`
	Icon         pgtype.Text        `json:"icon"`
	IsVisible    pgtype.Bool        `json:"is_visible"`
	VisibleFrom  pgtype.Timestamptz `json:"visible_from"`
	VisibleUntil pgtype.Timestamptz `json:"visible_until"`
}

func (q *Queries) UpdateBioPageLink(ctx context.Context, arg UpdateBioPageLinkParams) (BioPageLink, error) {
	row := q.db.QueryRow(ctx, updateBioPageLink,
		arg.ID,
		arg.Title,
		arg.Url,
		arg.Icon,
		arg.IsVisible,
		arg.VisibleFrom,
		arg.VisibleUntil,
	)
	var i BioPageLink
	err := row.Scan(
		&i.ID,
		&i.BioPageID,
		&i.Title,
		&i.Url,
		&i.Icon,
		&i.Position,
		&i.IsVisible,
		&i.VisibleFrom,
		&i.VisibleUntil,
		&i.ClickCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBioPageLink = `-- name: DeleteBioPageLink :exec
DELETE FROM bio_page_links
WHERE id = $1
`

func (q *Queries) DeleteBioPageLink(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteBioPageLink, id)
	return err
}

const updateBioPageLinkPosition = `-- name: UpdateBioPageLinkPosition :exec
UPDATE bio_page_links
SET position = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateBioPageLinkPositionParams struct {
	ID       uuid.UUID `json:"id"`
	Position int32     `json:"position"`
}

func (q *Queries) UpdateBioPageLinkPosition(ctx context.Context, arg UpdateBioPageLinkPositionParams) error {
	_, err := q.db.Exec(ctx, updateBioPageLinkPosition, arg.ID, arg.Position)
	return err
}

const incrementBioPageLinkClickCount = `-- name: IncrementBioPageLinkClickCount :exec
UPDATE bio_page_links
SET click_count = click_count + 1
WHERE id = $1
`

func (q *Queries) IncrementBioPageLinkClickCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementBioPageLinkClickCount, id)
	return err
}

const getMaxBioPageLinkPosition = `-- name: GetMaxBioPageLinkPosition :one
SELECT COALESCE(MAX(position), -1)::integer AS max_position FROM bio_page_links
WHERE bio_page_id = $1
`

func (q *Queries) GetMaxBioPageLinkPosition(ctx context.Context, bioPageID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getMaxBioPageLinkPosition, bioPageID)
	var maxPosition int32
	err := row.Scan(&maxPosition)
	return maxPosition, err
}
