// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: clicks.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getClicksByLinkID = `-- name: GetClicksByLinkID :many
SELECT id, link_id, clicked_at, visitor_id, ip_address, user_agent, referer, country_code, region, city, device_type, browser, browser_version, os, os_version, is_bot, utm_source, utm_medium, utm_campaign FROM clicks
WHERE link_id = $1
    AND clicked_at >= $2
    AND clicked_at <= $3
ORDER BY clicked_at DESC
LIMIT $4 OFFSET $5
`

type GetClicksByLinkIDParams struct {
	LinkID      uuid.UUID          `json:"link_id"`
	ClickedAt   pgtype.Timestamptz `json:"clicked_at"`
	ClickedAt_2 pgtype.Timestamptz `json:"clicked_at_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) GetClicksByLinkID(ctx context.Context, arg GetClicksByLinkIDParams) ([]Click, error) {
	rows, err := q.db.Query(ctx, getClicksByLinkID,
		arg.LinkID,
		arg.ClickedAt,
		arg.ClickedAt_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Click{}
	for rows.Next() {
		var i Click
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.ClickedAt,
			&i.VisitorID,
			&i.IpAddress,
			&i.UserAgent,
			&i.Referer,
			&i.CountryCode,
			&i.Region,
			&i.City,
			&i.DeviceType,
			&i.Browser,
			&i.BrowserVersion,
			&i.Os,
			&i.OsVersion,
			&i.IsBot,
			&i.UtmSource,
			&i.UtmMedium,
			&i.UtmCampaign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertClick = `-- name: InsertClick :exec
INSERT INTO clicks (
    link_id, clicked_at, visitor_id, ip_address, user_agent, referer,
    country_code, region, city, device_type, browser, browser_version,
    os, os_version, is_bot, utm_source, utm_medium, utm_campaign
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)
`

type InsertClickParams struct {
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

func (q *Queries) InsertClick(ctx context.Context, arg InsertClickParams) error {
	_, err := q.db.Exec(ctx, insertClick,
		arg.LinkID,
		arg.ClickedAt,
		arg.VisitorID,
		arg.IpAddress,
		arg.UserAgent,
		arg.Referer,
		arg.CountryCode,
		arg.Region,
		arg.City,
		arg.DeviceType,
		arg.Browser,
		arg.BrowserVersion,
		arg.Os,
		arg.OsVersion,
		arg.IsBot,
		arg.UtmSource,
		arg.UtmMedium,
		arg.UtmCampaign,
	)
	return err
}
