// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: domains.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDomain = `-- name: CreateDomain :one
INSERT INTO domains (workspace_id, domain)
VALUES ($1, $2)
RETURNING id, workspace_id, domain, is_verified, verified_at, ssl_status, ssl_expires_at, dns_records, last_dns_check_at, default_redirect_url, custom_404_url, created_at, updated_at, deleted_at
`

type CreateDomainParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Domain      string    `json:"domain"`
}

func (q *Queries) CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, createDomain, arg.WorkspaceID, arg.Domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.DnsRecords,
		&i.LastDnsCheckAt,
		&i.DefaultRedirectUrl,
		&i.Custom404Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDomainByDomain = `-- name: GetDomainByDomain :one
SELECT id, workspace_id, domain, is_verified, verified_at, ssl_status, ssl_expires_at, dns_records, last_dns_check_at, default_redirect_url, custom_404_url, created_at, updated_at, deleted_at FROM domains
WHERE domain = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDomainByDomain(ctx context.Context, domain string) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByDomain, domain)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.DnsRecords,
		&i.LastDnsCheckAt,
		&i.DefaultRedirectUrl,
		&i.Custom404Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDomainByID = `-- name: GetDomainByID :one
SELECT id, workspace_id, domain, is_verified, verified_at, ssl_status, ssl_expires_at, dns_records, last_dns_check_at, default_redirect_url, custom_404_url, created_at, updated_at, deleted_at FROM domains
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error) {
	row := q.db.QueryRow(ctx, getDomainByID, id)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.DnsRecords,
		&i.LastDnsCheckAt,
		&i.DefaultRedirectUrl,
		&i.Custom404Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDomainsForWorkspace = `-- name: ListDomainsForWorkspace :many
SELECT id, workspace_id, domain, is_verified, verified_at, ssl_status, ssl_expires_at, dns_records, last_dns_check_at, default_redirect_url, custom_404_url, created_at, updated_at, deleted_at FROM domains
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDomainsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Domain, error) {
	rows, err := q.db.Query(ctx, listDomainsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Domain{}
	for rows.Next() {
		var i Domain
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Domain,
			&i.IsVerified,
			&i.VerifiedAt,
			&i.SslStatus,
			&i.SslExpiresAt,
			&i.DnsRecords,
			&i.LastDnsCheckAt,
			&i.DefaultRedirectUrl,
			&i.Custom404Url,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteDomain = `-- name: SoftDeleteDomain :exec
UPDATE domains
SET deleted_at = NOW(), updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteDomain(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteDomain, id)
	return err
}

const getDomainCountForWorkspace = `-- name: GetDomainCountForWorkspace :one
SELECT COUNT(*) AS count FROM domains
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDomainCountForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getDomainCountForWorkspace, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateDomain = `-- name: UpdateDomain :one
UPDATE domains
SET
    is_verified = COALESCE($2, is_verified),
    verified_at = COALESCE($3, verified_at),
    ssl_status = COALESCE($4, ssl_status),
    ssl_expires_at = COALESCE($5, ssl_expires_at),
    dns_records = COALESCE($6, dns_records),
    last_dns_check_at = COALESCE($7, last_dns_check_at),
    default_redirect_url = COALESCE($8, default_redirect_url),
    custom_404_url = COALESCE($9, custom_404_url),
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, workspace_id, domain, is_verified, verified_at, ssl_status, ssl_expires_at, dns_records, last_dns_check_at, default_redirect_url, custom_404_url, created_at, updated_at, deleted_at
`

type UpdateDomainParams struct {
	ID                 uuid.UUID          `json:"id"`
	IsVerified         pgtype.Bool        `json:"is_verified"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	SslStatus          pgtype.Text        `json:"ssl_status"`
	SslExpiresAt       pgtype.Timestamptz `json:"ssl_expires_at"`
	DnsRecords         []byte             `json:"dns_records"`
	LastDnsCheckAt     pgtype.Timestamptz `json:"last_dns_check_at"`
	DefaultRedirectUrl pgtype.Text        `json:"default_redirect_url"`
	Custom404Url       pgtype.Text        `json:"custom_404_url"`
}

func (q *Queries) UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error) {
	row := q.db.QueryRow(ctx, updateDomain,
		arg.ID,
		arg.IsVerified,
		arg.VerifiedAt,
		arg.SslStatus,
		arg.SslExpiresAt,
		arg.DnsRecords,
		arg.LastDnsCheckAt,
		arg.DefaultRedirectUrl,
		arg.Custom404Url,
	)
	var i Domain
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Domain,
		&i.IsVerified,
		&i.VerifiedAt,
		&i.SslStatus,
		&i.SslExpiresAt,
		&i.DnsRecords,
		&i.LastDnsCheckAt,
		&i.DefaultRedirectUrl,
		&i.Custom404Url,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
