// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: link_rules.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLinkRule = `-- name: CreateLinkRule :one
INSERT INTO link_rules (
    link_id, rule_type, priority, is_active, conditions, destination_url, weight
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, link_id, rule_type, priority, is_active, conditions, destination_url, weight, created_at, updated_at
`

type CreateLinkRuleParams struct {
	LinkID         uuid.UUID       `json:"link_id"`
	RuleType       string          `json:"rule_type"`
	Priority       int32           `json:"priority"`
	IsActive       bool            `json:"is_active"`
	Conditions     json.RawMessage `json:"conditions"`
	DestinationUrl string          `json:"destination_url"`
	Weight         pgtype.Int4     `json:"weight"`
}

func (q *Queries) CreateLinkRule(ctx context.Context, arg CreateLinkRuleParams) (LinkRule, error) {
	row := q.db.QueryRow(ctx, createLinkRule,
		arg.LinkID,
		arg.RuleType,
		arg.Priority,
		arg.IsActive,
		arg.Conditions,
		arg.DestinationUrl,
		arg.Weight,
	)
	var i LinkRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.RuleType,
		&i.Priority,
		&i.IsActive,
		&i.Conditions,
		&i.DestinationUrl,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLinkRule = `-- name: DeleteLinkRule :exec
DELETE FROM link_rules WHERE id = $1
`

func (q *Queries) DeleteLinkRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteLinkRule, id)
	return err
}

const getActiveRulesForLink = `-- name: GetActiveRulesForLink :many
SELECT id, link_id, rule_type, priority, is_active, conditions, destination_url, weight, created_at, updated_at FROM link_rules
WHERE link_id = $1 AND is_active = TRUE
ORDER BY priority ASC
`

func (q *Queries) GetActiveRulesForLink(ctx context.Context, linkID uuid.UUID) ([]LinkRule, error) {
	rows, err := q.db.Query(ctx, getActiveRulesForLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LinkRule{}
	for rows.Next() {
		var i LinkRule
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.RuleType,
			&i.Priority,
			&i.IsActive,
			&i.Conditions,
			&i.DestinationUrl,
			&i.Weight,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLinkRuleByID = `-- name: GetLinkRuleByID :one
SELECT id, link_id, rule_type, priority, is_active, conditions, destination_url, weight, created_at, updated_at FROM link_rules WHERE id = $1
`

func (q *Queries) GetLinkRuleByID(ctx context.Context, id uuid.UUID) (LinkRule, error) {
	row := q.db.QueryRow(ctx, getLinkRuleByID, id)
	var i LinkRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.RuleType,
		&i.Priority,
		&i.IsActive,
		&i.Conditions,
		&i.DestinationUrl,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLinkRule = `-- name: UpdateLinkRule :one
UPDATE link_rules
SET
    rule_type = COALESCE($2, rule_type),
    priority = COALESCE($3, priority),
    is_active = COALESCE($4, is_active),
    conditions = COALESCE($5, conditions),
    destination_url = COALESCE($6, destination_url),
    weight = COALESCE($7, weight),
    updated_at = NOW()
WHERE id = $1
RETURNING id, link_id, rule_type, priority, is_active, conditions, destination_url, weight, created_at, updated_at
`

type UpdateLinkRuleParams struct {
	ID             uuid.UUID   `json:"id"`
	RuleType       pgtype.Text `json:"rule_type"`
	Priority       pgtype.Int4 `json:"priority"`
	IsActive       pgtype.Bool `json:"is_active"`
	Conditions     []byte      `json:"conditions"`
	DestinationUrl pgtype.Text `json:"destination_url"`
	Weight         pgtype.Int4 `json:"weight"`
}

func (q *Queries) UpdateLinkRule(ctx context.Context, arg UpdateLinkRuleParams) (LinkRule, error) {
	row := q.db.QueryRow(ctx, updateLinkRule,
		arg.ID,
		arg.RuleType,
		arg.Priority,
		arg.IsActive,
		arg.Conditions,
		arg.DestinationUrl,
		arg.Weight,
	)
	var i LinkRule
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.RuleType,
		&i.Priority,
		&i.IsActive,
		&i.Conditions,
		&i.DestinationUrl,
		&i.Weight,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
