// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Name         string             `json:"name"`
	KeyHash      string             `json:"key_hash"`
	KeyPrefix    string             `json:"key_prefix"`
	Scopes       []string           `json:"scopes"`
	LastUsedAt   pgtype.Timestamptz `json:"last_used_at"`
	RequestCount int64              `json:"request_count"`
	RateLimit    pgtype.Int4        `json:"rate_limit"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
}

type AuditLog struct {
	ID           uuid.UUID          `json:"id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.UUID        `json:"resource_id"`
	OldValues    []byte             `json:"old_values"`
	NewValues    []byte             `json:"new_values"`
	Metadata     []byte             `json:"metadata"`
	IpAddress    string             `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BioPage struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Slug            string             `json:"slug"`
	Title           string             `json:"title"`
	Bio             pgtype.Text        `json:"bio"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	ThemeID         pgtype.UUID        `json:"theme_id"`
	CustomCss       pgtype.Text        `json:"custom_css"`
	MetaTitle       pgtype.Text        `json:"meta_title"`
	MetaDescription pgtype.Text        `json:"meta_description"`
	OgImageUrl      pgtype.Text        `json:"og_image_url"`
	IsPublished     bool               `json:"is_published"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type BioPageLink struct {
	ID           uuid.UUID          `json:"id"`
	BioPageID    uuid.UUID          `json:"bio_page_id"`
	Title        string             `json:"title"`
	Url          string             `json:"url"`
	Icon         pgtype.Text        `json:"icon"`
	Position     int32              `json:"position"`
	IsVisible    bool               `json:"is_visible"`
	VisibleFrom  pgtype.Timestamptz `json:"visible_from"`
	VisibleUntil pgtype.Timestamptz `json:"visible_until"`
	ClickCount   int64              `json:"click_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Click struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202501 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202502 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202503 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202504 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202505 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202506 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202507 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202508 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202509 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202510 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202511 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202512 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202601 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202602 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202603 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202604 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202605 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Clicks202606 struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	ClickedAt      pgtype.Timestamptz `json:"clicked_at"`
	VisitorID      pgtype.Text        `json:"visitor_id"`
	IpAddress      string             `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	Referer        pgtype.Text        `json:"referer"`
	CountryCode    pgtype.Text        `json:"country_code"`
	Region         pgtype.Text        `json:"region"`
	City           pgtype.Text        `json:"city"`
	DeviceType     pgtype.Text        `json:"device_type"`
	Browser        pgtype.Text        `json:"browser"`
	BrowserVersion pgtype.Text        `json:"browser_version"`
	Os             pgtype.Text        `json:"os"`
	OsVersion      pgtype.Text        `json:"os_version"`
	IsBot          bool               `json:"is_bot"`
	UtmSource      pgtype.Text        `json:"utm_source"`
	UtmMedium      pgtype.Text        `json:"utm_medium"`
	UtmCampaign    pgtype.Text        `json:"utm_campaign"`
}

type Domain struct {
	ID                 uuid.UUID          `json:"id"`
	WorkspaceID        uuid.UUID          `json:"workspace_id"`
	Domain             string             `json:"domain"`
	IsVerified         bool               `json:"is_verified"`
	VerifiedAt         pgtype.Timestamptz `json:"verified_at"`
	SslStatus          string             `json:"ssl_status"`
	SslExpiresAt       pgtype.Timestamptz `json:"ssl_expires_at"`
	DnsRecords         json.RawMessage    `json:"dns_records"`
	LastDnsCheckAt     pgtype.Timestamptz `json:"last_dns_check_at"`
	DefaultRedirectUrl pgtype.Text        `json:"default_redirect_url"`
	Custom404Url       pgtype.Text        `json:"custom_404_url"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type Link struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	WorkspaceID  uuid.UUID          `json:"workspace_id"`
	DomainID     pgtype.UUID        `json:"domain_id"`
	Url          string             `json:"url"`
	ShortCode    string             `json:"short_code"`
	Title        pgtype.Text        `json:"title"`
	Description  pgtype.Text        `json:"description"`
	FaviconUrl   pgtype.Text        `json:"favicon_url"`
	OgImageUrl   pgtype.Text        `json:"og_image_url"`
	IsActive     bool               `json:"is_active"`
	PasswordHash pgtype.Text        `json:"password_hash"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	MaxClicks    pgtype.Int4        `json:"max_clicks"`
	UtmSource    pgtype.Text        `json:"utm_source"`
	UtmMedium    pgtype.Text        `json:"utm_medium"`
	UtmCampaign  pgtype.Text        `json:"utm_campaign"`
	UtmTerm      pgtype.Text        `json:"utm_term"`
	UtmContent   pgtype.Text        `json:"utm_content"`
	TotalClicks  int64              `json:"total_clicks"`
	UniqueClicks int64              `json:"unique_clicks"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type LinkRule struct {
	ID             uuid.UUID          `json:"id"`
	LinkID         uuid.UUID          `json:"link_id"`
	RuleType       string             `json:"rule_type"`
	Priority       int32              `json:"priority"`
	IsActive       bool               `json:"is_active"`
	Conditions     json.RawMessage    `json:"conditions"`
	DestinationUrl string             `json:"destination_url"`
	Weight         pgtype.Int4        `json:"weight"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type LinkTag struct {
	LinkID uuid.UUID `json:"link_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type PasswordReset struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type QrCode struct {
	ID              uuid.UUID          `json:"id"`
	LinkID          uuid.UUID          `json:"link_id"`
	QrType          string             `json:"qr_type"`
	ErrorCorrection string             `json:"error_correction"`
	ForegroundColor string             `json:"foreground_color"`
	BackgroundColor string             `json:"background_color"`
	LogoUrl         pgtype.Text        `json:"logo_url"`
	PngUrl          pgtype.Text        `json:"png_url"`
	SvgUrl          pgtype.Text        `json:"svg_url"`
	DotStyle        string             `json:"dot_style"`
	CornerStyle     string             `json:"corner_style"`
	Size            int32              `json:"size"`
	Margin          int32              `json:"margin"`
	ScanCount       int64              `json:"scan_count"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	IpAddress        string             `json:"ip_address"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	DeviceName       pgtype.Text        `json:"device_name"`
	IsRevoked        bool               `json:"is_revoked"`
	LastActiveAt     pgtype.Timestamptz `json:"last_active_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
}

type Subscription struct {
	ID                   uuid.UUID          `json:"id"`
	WorkspaceID          uuid.UUID          `json:"workspace_id"`
	StripeSubscriptionID pgtype.Text        `json:"stripe_subscription_id"`
	StripeCustomerID     string             `json:"stripe_customer_id"`
	StripePriceID        string             `json:"stripe_price_id"`
	Plan                 string             `json:"plan"`
	Status               string             `json:"status"`
	CurrentPeriodStart   pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd     pgtype.Timestamptz `json:"current_period_end"`
	CancelAtPeriodEnd    bool               `json:"cancel_at_period_end"`
	UsageLinkCount       int32              `json:"usage_link_count"`
	UsageClickCount      int64              `json:"usage_click_count"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Tag struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	Name        string             `json:"name"`
	Color       string             `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	PasswordHash     string             `json:"password_hash"`
	Name             string             `json:"name"`
	AvatarUrl        pgtype.Text        `json:"avatar_url"`
	EmailVerifiedAt  pgtype.Timestamptz `json:"email_verified_at"`
	TwoFactorEnabled bool               `json:"two_factor_enabled"`
	TwoFactorSecret  pgtype.Text        `json:"two_factor_secret"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Webhook struct {
	ID              uuid.UUID          `json:"id"`
	WorkspaceID     uuid.UUID          `json:"workspace_id"`
	Url             string             `json:"url"`
	Secret          string             `json:"secret"`
	Events          []string           `json:"events"`
	IsActive        bool               `json:"is_active"`
	FailureCount    int32              `json:"failure_count"`
	LastTriggeredAt pgtype.Timestamptz `json:"last_triggered_at"`
	LastSuccessAt   pgtype.Timestamptz `json:"last_success_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type WebhookDelivery struct {
	ID             uuid.UUID          `json:"id"`
	WebhookID      uuid.UUID          `json:"webhook_id"`
	Event          string             `json:"event"`
	Payload        json.RawMessage    `json:"payload"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	LastAttemptAt  pgtype.Timestamptz `json:"last_attempt_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Workspace struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Slug      string             `json:"slug"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	Plan      string             `json:"plan"`
	Settings  json.RawMessage    `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type WorkspaceMember struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	UserID      uuid.UUID          `json:"user_id"`
	Role        string             `json:"role"`
	InvitedBy   pgtype.UUID        `json:"invited_by"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
