// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_resets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordReset = `-- name: CreatePasswordReset :one
INSERT INTO password_resets (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, used_at, created_at, expires_at
`

type CreatePasswordResetParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, createPasswordReset, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredPasswordResets = `-- name: DeleteExpiredPasswordResets :exec
DELETE FROM password_resets
WHERE expires_at < NOW() OR used_at IS NOT NULL
`

func (q *Queries) DeleteExpiredPasswordResets(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResets)
	return err
}

const getPasswordResetByToken = `-- name: GetPasswordResetByToken :one
SELECT id, user_id, token_hash, used_at, created_at, expires_at FROM password_resets
WHERE token_hash = $1
    AND used_at IS NULL
    AND expires_at > NOW()
`

func (q *Queries) GetPasswordResetByToken(ctx context.Context, tokenHash string) (PasswordReset, error) {
	row := q.db.QueryRow(ctx, getPasswordResetByToken, tokenHash)
	var i PasswordReset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.UsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const markPasswordResetUsed = `-- name: MarkPasswordResetUsed :exec
UPDATE password_resets
SET used_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markPasswordResetUsed, id)
	return err
}
