// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: qr_codes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createQRCode = `-- name: CreateQRCode :one
INSERT INTO qr_codes (
    link_id,
    qr_type,
    error_correction,
    foreground_color,
    background_color,
    logo_url,
    png_url,
    svg_url,
    dot_style,
    corner_style,
    size,
    margin
) VALUES (
    $1, $2, $3, $4, $5,
    $6,
    $7,
    $8,
    $9, $10, $11, $12
)
RETURNING id, link_id, qr_type, error_correction, foreground_color, background_color, logo_url, png_url, svg_url, dot_style, corner_style, size, margin, scan_count, created_at, updated_at
`

type CreateQRCodeParams struct {
	LinkID          uuid.UUID   `json:"link_id"`
	QrType          string      `json:"qr_type"`
	ErrorCorrection string      `json:"error_correction"`
	ForegroundColor string      `json:"foreground_color"`
	BackgroundColor string      `json:"background_color"`
	LogoUrl         pgtype.Text `json:"logo_url"`
	PngUrl          pgtype.Text `json:"png_url"`
	SvgUrl          pgtype.Text `json:"svg_url"`
	DotStyle        string      `json:"dot_style"`
	CornerStyle     string      `json:"corner_style"`
	Size            int32       `json:"size"`
	Margin          int32       `json:"margin"`
}

func (q *Queries) CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, createQRCode,
		arg.LinkID,
		arg.QrType,
		arg.ErrorCorrection,
		arg.ForegroundColor,
		arg.BackgroundColor,
		arg.LogoUrl,
		arg.PngUrl,
		arg.SvgUrl,
		arg.DotStyle,
		arg.CornerStyle,
		arg.Size,
		arg.Margin,
	)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.QrType,
		&i.ErrorCorrection,
		&i.ForegroundColor,
		&i.BackgroundColor,
		&i.LogoUrl,
		&i.PngUrl,
		&i.SvgUrl,
		&i.DotStyle,
		&i.CornerStyle,
		&i.Size,
		&i.Margin,
		&i.ScanCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQRCodeByID = `-- name: GetQRCodeByID :one
SELECT id, link_id, qr_type, error_correction, foreground_color, background_color, logo_url, png_url, svg_url, dot_style, corner_style, size, margin, scan_count, created_at, updated_at FROM qr_codes
WHERE id = $1
`

func (q *Queries) GetQRCodeByID(ctx context.Context, id uuid.UUID) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQRCodeByID, id)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.QrType,
		&i.ErrorCorrection,
		&i.ForegroundColor,
		&i.BackgroundColor,
		&i.LogoUrl,
		&i.PngUrl,
		&i.SvgUrl,
		&i.DotStyle,
		&i.CornerStyle,
		&i.Size,
		&i.Margin,
		&i.ScanCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getQRCodeByLinkID = `-- name: GetQRCodeByLinkID :one
SELECT id, link_id, qr_type, error_correction, foreground_color, background_color, logo_url, png_url, svg_url, dot_style, corner_style, size, margin, scan_count, created_at, updated_at FROM qr_codes
WHERE link_id = $1
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetQRCodeByLinkID(ctx context.Context, linkID uuid.UUID) (QrCode, error) {
	row := q.db.QueryRow(ctx, getQRCodeByLinkID, linkID)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.QrType,
		&i.ErrorCorrection,
		&i.ForegroundColor,
		&i.BackgroundColor,
		&i.LogoUrl,
		&i.PngUrl,
		&i.SvgUrl,
		&i.DotStyle,
		&i.CornerStyle,
		&i.Size,
		&i.Margin,
		&i.ScanCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQRCodesForLink = `-- name: ListQRCodesForLink :many
SELECT id, link_id, qr_type, error_correction, foreground_color, background_color, logo_url, png_url, svg_url, dot_style, corner_style, size, margin, scan_count, created_at, updated_at FROM qr_codes
WHERE link_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListQRCodesForLink(ctx context.Context, linkID uuid.UUID) ([]QrCode, error) {
	rows, err := q.db.Query(ctx, listQRCodesForLink, linkID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []QrCode{}
	for rows.Next() {
		var i QrCode
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.QrType,
			&i.ErrorCorrection,
			&i.ForegroundColor,
			&i.BackgroundColor,
			&i.LogoUrl,
			&i.PngUrl,
			&i.SvgUrl,
			&i.DotStyle,
			&i.CornerStyle,
			&i.Size,
			&i.Margin,
			&i.ScanCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQRCode = `-- name: UpdateQRCode :one
UPDATE qr_codes SET
    qr_type = COALESCE($2, qr_type),
    error_correction = COALESCE($3, error_correction),
    foreground_color = COALESCE($4, foreground_color),
    background_color = COALESCE($5, background_color),
    logo_url = COALESCE($6, logo_url),
    png_url = COALESCE($7, png_url),
    svg_url = COALESCE($8, svg_url),
    dot_style = COALESCE($9, dot_style),
    corner_style = COALESCE($10, corner_style),
    size = COALESCE($11, size),
    margin = COALESCE($12, margin),
    updated_at = NOW()
WHERE id = $1
RETURNING id, link_id, qr_type, error_correction, foreground_color, background_color, logo_url, png_url, svg_url, dot_style, corner_style, size, margin, scan_count, created_at, updated_at
`

type UpdateQRCodeParams struct {
	ID              uuid.UUID   `json:"id"`
	QrType          pgtype.Text `json:"qr_type"`
	ErrorCorrection pgtype.Text `json:"error_correction"`
	ForegroundColor pgtype.Text `json:"foreground_color"`
	BackgroundColor pgtype.Text `json:"background_color"`
	LogoUrl         pgtype.Text `json:"logo_url"`
	PngUrl          pgtype.Text `json:"png_url"`
	SvgUrl          pgtype.Text `json:"svg_url"`
	DotStyle        pgtype.Text `json:"dot_style"`
	CornerStyle     pgtype.Text `json:"corner_style"`
	Size            pgtype.Int4 `json:"size"`
	Margin          pgtype.Int4 `json:"margin"`
}

func (q *Queries) UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (QrCode, error) {
	row := q.db.QueryRow(ctx, updateQRCode,
		arg.ID,
		arg.QrType,
		arg.ErrorCorrection,
		arg.ForegroundColor,
		arg.BackgroundColor,
		arg.LogoUrl,
		arg.PngUrl,
		arg.SvgUrl,
		arg.DotStyle,
		arg.CornerStyle,
		arg.Size,
		arg.Margin,
	)
	var i QrCode
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.QrType,
		&i.ErrorCorrection,
		&i.ForegroundColor,
		&i.BackgroundColor,
		&i.LogoUrl,
		&i.PngUrl,
		&i.SvgUrl,
		&i.DotStyle,
		&i.CornerStyle,
		&i.Size,
		&i.Margin,
		&i.ScanCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQRCode = `-- name: DeleteQRCode :exec
DELETE FROM qr_codes
WHERE id = $1
`

func (q *Queries) DeleteQRCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQRCode, id)
	return err
}

const incrementQRScanCount = `-- name: IncrementQRScanCount :exec
UPDATE qr_codes
SET scan_count = scan_count + 1
WHERE id = $1
`

func (q *Queries) IncrementQRScanCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementQRScanCount, id)
	return err
}
