// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	CountRecentWebhookFailures(ctx context.Context, webhookID uuid.UUID) (int64, error)
	CountWebhookDeliveries(ctx context.Context, webhookID uuid.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) error
	CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	CreateBioPage(ctx context.Context, arg CreateBioPageParams) (BioPage, error)
	CreateBioPageLink(ctx context.Context, arg CreateBioPageLinkParams) (BioPageLink, error)
	CreateDomain(ctx context.Context, arg CreateDomainParams) (Domain, error)
	CreateLink(ctx context.Context, arg CreateLinkParams) (Link, error)
	CreateQRCode(ctx context.Context, arg CreateQRCodeParams) (QrCode, error)
	DeleteQRCode(ctx context.Context, id uuid.UUID) error
	DeleteWebhook(ctx context.Context, id uuid.UUID) error
	DisableWebhook(ctx context.Context, id uuid.UUID) error
	GetQRCodeByID(ctx context.Context, id uuid.UUID) (QrCode, error)
	GetQRCodeByLinkID(ctx context.Context, linkID uuid.UUID) (QrCode, error)
	IncrementQRScanCount(ctx context.Context, id uuid.UUID) error
	ListQRCodesForLink(ctx context.Context, linkID uuid.UUID) ([]QrCode, error)
	UpdateQRCode(ctx context.Context, arg UpdateQRCodeParams) (QrCode, error)
	CreateLinkRule(ctx context.Context, arg CreateLinkRuleParams) (LinkRule, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (PasswordReset, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error)
	DeleteBioPageLink(ctx context.Context, id uuid.UUID) error
	DeleteExpiredPasswordResets(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLinkRule(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]Webhook, error)
	GetPendingWebhookDeliveries(ctx context.Context) ([]WebhookDelivery, error)
	GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error)
	GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error)
	GetActiveRulesForLink(ctx context.Context, linkID uuid.UUID) ([]LinkRule, error)
	GetBioPageByID(ctx context.Context, id uuid.UUID) (BioPage, error)
	GetBioPageBySlug(ctx context.Context, slug string) (BioPage, error)
	GetBioPageCountForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	GetBioPageLinkByID(ctx context.Context, id uuid.UUID) (BioPageLink, error)
	GetMaxBioPageLinkPosition(ctx context.Context, bioPageID uuid.UUID) (int32, error)
	GetClicksByLinkID(ctx context.Context, arg GetClicksByLinkIDParams) ([]Click, error)
	GetDomainByDomain(ctx context.Context, domain string) (Domain, error)
	GetDomainByID(ctx context.Context, id uuid.UUID) (Domain, error)
	GetMemberCountForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	GetLinkByID(ctx context.Context, id uuid.UUID) (Link, error)
	GetLinkByShortCode(ctx context.Context, shortCode string) (Link, error)
	GetLinkByURL(ctx context.Context, arg GetLinkByURLParams) (Link, error)
	GetLinkCountForWorkspace(ctx context.Context, workspaceID uuid.UUID) (int64, error)
	GetLinkQuickStats(ctx context.Context, id uuid.UUID) (GetLinkQuickStatsRow, error)
	GetLinkRuleByID(ctx context.Context, id uuid.UUID) (LinkRule, error)
	GetPasswordResetByToken(ctx context.Context, tokenHash string) (PasswordReset, error)
	GetSessionByToken(ctx context.Context, refreshTokenHash string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkspaceCountForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	GetWorkspaceByID(ctx context.Context, id uuid.UUID) (Workspace, error)
	GetWorkspaceBySlug(ctx context.Context, slug string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (WorkspaceMember, error)
	IncrementBioPageLinkClickCount(ctx context.Context, id uuid.UUID) error
	IncrementWebhookFailureCount(ctx context.Context, id uuid.UUID) error
	IncrementLinkClicks(ctx context.Context, id uuid.UUID) error
	IncrementLinkUniqueClicks(ctx context.Context, id uuid.UUID) error
	InsertClick(ctx context.Context, arg InsertClickParams) error
	ListAPIKeysForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ApiKey, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error)
	ListWebhooksForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Webhook, error)
	ListAuditLogsForWorkspace(ctx context.Context, arg ListAuditLogsForWorkspaceParams) ([]AuditLog, error)
	ListBioPageLinks(ctx context.Context, bioPageID uuid.UUID) ([]BioPageLink, error)
	ListBioPagesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]BioPage, error)
	ListDomainsForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Domain, error)
	ListLinksForWorkspace(ctx context.Context, arg ListLinksForWorkspaceParams) ([]ListLinksForWorkspaceRow, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID uuid.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspacesForUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error)
	MarkPasswordResetUsed(ctx context.Context, id uuid.UUID) error
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) error
	ResetWebhookFailureCount(ctx context.Context, id uuid.UUID) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	SetEmailVerified(ctx context.Context, id uuid.UUID) error
	ShortCodeExists(ctx context.Context, shortCode string) (bool, error)
	SoftDeleteBioPage(ctx context.Context, id uuid.UUID) error
	SoftDeleteDomain(ctx context.Context, id uuid.UUID) error
	SoftDeleteLink(ctx context.Context, id uuid.UUID) error
	SoftDeleteUser(ctx context.Context, id uuid.UUID) error
	SoftDeleteWorkspace(ctx context.Context, id uuid.UUID) error
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateBioPage(ctx context.Context, arg UpdateBioPageParams) (BioPage, error)
	UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error)
	UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error
	UpdateWebhookLastTriggered(ctx context.Context, id uuid.UUID) error
	UpdateBioPageLink(ctx context.Context, arg UpdateBioPageLinkParams) (BioPageLink, error)
	UpdateBioPageLinkPosition(ctx context.Context, arg UpdateBioPageLinkPositionParams) error
	UpdateDomain(ctx context.Context, arg UpdateDomainParams) (Domain, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (Link, error)
	UpdateLinkRule(ctx context.Context, arg UpdateLinkRuleParams) (LinkRule, error)
	UpdateMemberRole(ctx context.Context, arg UpdateMemberRoleParams) (WorkspaceMember, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	UpdateWorkspace(ctx context.Context, arg UpdateWorkspaceParams) (Workspace, error)
	UpdateWorkspaceOwner(ctx context.Context, arg UpdateWorkspaceOwnerParams) (Workspace, error)
}

var _ Querier = (*Queries)(nil)
