// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scim.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSCIMToken = `-- name: CreateSCIMToken :one
INSERT INTO scim_tokens (
    workspace_id, token_hash, token_prefix, name, expires_at
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, token_hash, token_prefix, name, is_active, last_used_at, created_at, expires_at
`

type CreateSCIMTokenParams struct {
	WorkspaceID uuid.UUID          `json:"workspace_id"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	Name        string             `json:"name"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSCIMToken(ctx context.Context, arg CreateSCIMTokenParams) (ScimToken, error) {
	row := q.db.QueryRow(ctx, createSCIMToken,
		arg.WorkspaceID,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Name,
		arg.ExpiresAt,
	)
	var i ScimToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getSCIMTokenByHash = `-- name: GetSCIMTokenByHash :one
SELECT id, workspace_id, token_hash, token_prefix, name, is_active, last_used_at, created_at, expires_at FROM scim_tokens
WHERE token_hash = $1 AND is_active = TRUE
`

func (q *Queries) GetSCIMTokenByHash(ctx context.Context, tokenHash string) (ScimToken, error) {
	row := q.db.QueryRow(ctx, getSCIMTokenByHash, tokenHash)
	var i ScimToken
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.Name,
		&i.IsActive,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listSCIMTokensForWorkspace = `-- name: ListSCIMTokensForWorkspace :many
SELECT id, workspace_id, token_hash, token_prefix, name, is_active, last_used_at, created_at, expires_at FROM scim_tokens
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSCIMTokensForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ScimToken, error) {
	rows, err := q.db.Query(ctx, listSCIMTokensForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimToken
	for rows.Next() {
		var i ScimToken
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.Name,
			&i.IsActive,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeSCIMToken = `-- name: RevokeSCIMToken :exec
UPDATE scim_tokens
SET is_active = FALSE
WHERE id = $1
`

func (q *Queries) RevokeSCIMToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSCIMToken, id)
	return err
}

const updateSCIMTokenLastUsed = `-- name: UpdateSCIMTokenLastUsed :exec
UPDATE scim_tokens
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateSCIMTokenLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSCIMTokenLastUsed, id)
	return err
}

const deleteSCIMToken = `-- name: DeleteSCIMToken :exec
DELETE FROM scim_tokens WHERE id = $1
`

func (q *Queries) DeleteSCIMToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSCIMToken, id)
	return err
}

const createSCIMSyncLog = `-- name: CreateSCIMSyncLog :exec
INSERT INTO scim_sync_log (
    workspace_id, operation, resource_type, external_id, status, details
)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateSCIMSyncLogParams struct {
	WorkspaceID  uuid.UUID       `json:"workspace_id"`
	Operation    string          `json:"operation"`
	ResourceType string          `json:"resource_type"`
	ExternalID   pgtype.Text     `json:"external_id"`
	Status       string          `json:"status"`
	Details      json.RawMessage `json:"details"`
}

func (q *Queries) CreateSCIMSyncLog(ctx context.Context, arg CreateSCIMSyncLogParams) error {
	_, err := q.db.Exec(ctx, createSCIMSyncLog,
		arg.WorkspaceID,
		arg.Operation,
		arg.ResourceType,
		arg.ExternalID,
		arg.Status,
		arg.Details,
	)
	return err
}

const listSCIMSyncLogs = `-- name: ListSCIMSyncLogs :many
SELECT id, workspace_id, operation, resource_type, external_id, status, details, created_at FROM scim_sync_log
WHERE workspace_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSCIMSyncLogsParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Limit       int32     `json:"limit"`
	Offset      int32     `json:"offset"`
}

func (q *Queries) ListSCIMSyncLogs(ctx context.Context, arg ListSCIMSyncLogsParams) ([]ScimSyncLog, error) {
	rows, err := q.db.Query(ctx, listSCIMSyncLogs, arg.WorkspaceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScimSyncLog
	for rows.Next() {
		var i ScimSyncLog
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Operation,
			&i.ResourceType,
			&i.ExternalID,
			&i.Status,
			&i.Details,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countSCIMSyncLogs = `-- name: CountSCIMSyncLogs :one
SELECT COUNT(*) FROM scim_sync_log
WHERE workspace_id = $1
`

func (q *Queries) CountSCIMSyncLogs(ctx context.Context, workspaceID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSCIMSyncLogs, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
