// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sso.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSSOConfigByWorkspace = `-- name: GetSSOConfigByWorkspace :one
SELECT id, workspace_id, provider, entity_id, sso_url, slo_url, certificate, idp_metadata_url, idp_metadata_xml, attribute_mapping, is_enabled, enforce_sso, allowed_domains, created_at, updated_at FROM sso_configs WHERE workspace_id = $1
`

func (q *Queries) GetSSOConfigByWorkspace(ctx context.Context, workspaceID uuid.UUID) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, getSSOConfigByWorkspace, workspaceID)
	var i SsoConfig
	err := row.Scan(
		&i.ID, &i.WorkspaceID, &i.Provider, &i.EntityID, &i.SsoUrl,
		&i.SloUrl, &i.Certificate, &i.IdpMetadataUrl, &i.IdpMetadataXml,
		&i.AttributeMapping, &i.IsEnabled, &i.EnforceSso, &i.AllowedDomains,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

type CreateSSOConfigParams struct {
	WorkspaceID      uuid.UUID       `json:"workspace_id"`
	Provider         string          `json:"provider"`
	EntityID         string          `json:"entity_id"`
	SsoUrl           string          `json:"sso_url"`
	SloUrl           pgtype.Text     `json:"slo_url"`
	Certificate      string          `json:"certificate"`
	IdpMetadataUrl   pgtype.Text     `json:"idp_metadata_url"`
	IdpMetadataXml   pgtype.Text     `json:"idp_metadata_xml"`
	AttributeMapping json.RawMessage `json:"attribute_mapping"`
	IsEnabled        bool            `json:"is_enabled"`
	EnforceSso       bool            `json:"enforce_sso"`
	AllowedDomains   []string        `json:"allowed_domains"`
}

const createSSOConfig = `-- name: CreateSSOConfig :one
INSERT INTO sso_configs (
    workspace_id, provider, entity_id, sso_url, slo_url,
    certificate, idp_metadata_url, idp_metadata_xml,
    attribute_mapping, is_enabled, enforce_sso, allowed_domains
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id, workspace_id, provider, entity_id, sso_url, slo_url, certificate, idp_metadata_url, idp_metadata_xml, attribute_mapping, is_enabled, enforce_sso, allowed_domains, created_at, updated_at
`

func (q *Queries) CreateSSOConfig(ctx context.Context, arg CreateSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, createSSOConfig,
		arg.WorkspaceID, arg.Provider, arg.EntityID, arg.SsoUrl, arg.SloUrl,
		arg.Certificate, arg.IdpMetadataUrl, arg.IdpMetadataXml,
		arg.AttributeMapping, arg.IsEnabled, arg.EnforceSso, arg.AllowedDomains,
	)
	var i SsoConfig
	err := row.Scan(
		&i.ID, &i.WorkspaceID, &i.Provider, &i.EntityID, &i.SsoUrl,
		&i.SloUrl, &i.Certificate, &i.IdpMetadataUrl, &i.IdpMetadataXml,
		&i.AttributeMapping, &i.IsEnabled, &i.EnforceSso, &i.AllowedDomains,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

type UpdateSSOConfigParams struct {
	WorkspaceID      uuid.UUID       `json:"workspace_id"`
	Provider         string          `json:"provider"`
	EntityID         string          `json:"entity_id"`
	SsoUrl           string          `json:"sso_url"`
	SloUrl           pgtype.Text     `json:"slo_url"`
	Certificate      string          `json:"certificate"`
	IdpMetadataUrl   pgtype.Text     `json:"idp_metadata_url"`
	IdpMetadataXml   pgtype.Text     `json:"idp_metadata_xml"`
	AttributeMapping json.RawMessage `json:"attribute_mapping"`
	IsEnabled        bool            `json:"is_enabled"`
	EnforceSso       bool            `json:"enforce_sso"`
	AllowedDomains   []string        `json:"allowed_domains"`
}

const updateSSOConfig = `-- name: UpdateSSOConfig :one
UPDATE sso_configs SET
    provider = $2,
    entity_id = $3,
    sso_url = $4,
    slo_url = $5,
    certificate = $6,
    idp_metadata_url = $7,
    idp_metadata_xml = $8,
    attribute_mapping = $9,
    is_enabled = $10,
    enforce_sso = $11,
    allowed_domains = $12,
    updated_at = NOW()
WHERE workspace_id = $1
RETURNING id, workspace_id, provider, entity_id, sso_url, slo_url, certificate, idp_metadata_url, idp_metadata_xml, attribute_mapping, is_enabled, enforce_sso, allowed_domains, created_at, updated_at
`

func (q *Queries) UpdateSSOConfig(ctx context.Context, arg UpdateSSOConfigParams) (SsoConfig, error) {
	row := q.db.QueryRow(ctx, updateSSOConfig,
		arg.WorkspaceID, arg.Provider, arg.EntityID, arg.SsoUrl, arg.SloUrl,
		arg.Certificate, arg.IdpMetadataUrl, arg.IdpMetadataXml,
		arg.AttributeMapping, arg.IsEnabled, arg.EnforceSso, arg.AllowedDomains,
	)
	var i SsoConfig
	err := row.Scan(
		&i.ID, &i.WorkspaceID, &i.Provider, &i.EntityID, &i.SsoUrl,
		&i.SloUrl, &i.Certificate, &i.IdpMetadataUrl, &i.IdpMetadataXml,
		&i.AttributeMapping, &i.IsEnabled, &i.EnforceSso, &i.AllowedDomains,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

const deleteSSOConfig = `-- name: DeleteSSOConfig :exec
DELETE FROM sso_configs WHERE workspace_id = $1
`

func (q *Queries) DeleteSSOConfig(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSOConfig, workspaceID)
	return err
}

// SSO Identity queries

type GetSSOIdentityByExternalIDParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	ExternalID  string    `json:"external_id"`
}

const getSSOIdentityByExternalID = `-- name: GetSSOIdentityByExternalID :one
SELECT id, user_id, workspace_id, provider, external_id, email, name, raw_attributes, last_login_at, created_at, updated_at FROM sso_identities WHERE workspace_id = $1 AND external_id = $2
`

func (q *Queries) GetSSOIdentityByExternalID(ctx context.Context, arg GetSSOIdentityByExternalIDParams) (SsoIdentity, error) {
	row := q.db.QueryRow(ctx, getSSOIdentityByExternalID, arg.WorkspaceID, arg.ExternalID)
	var i SsoIdentity
	err := row.Scan(
		&i.ID, &i.UserID, &i.WorkspaceID, &i.Provider, &i.ExternalID,
		&i.Email, &i.Name, &i.RawAttributes, &i.LastLoginAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

type GetSSOIdentityByUserIDParams struct {
	UserID      uuid.UUID `json:"user_id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

const getSSOIdentityByUserID = `-- name: GetSSOIdentityByUserID :one
SELECT id, user_id, workspace_id, provider, external_id, email, name, raw_attributes, last_login_at, created_at, updated_at FROM sso_identities WHERE user_id = $1 AND workspace_id = $2
`

func (q *Queries) GetSSOIdentityByUserID(ctx context.Context, arg GetSSOIdentityByUserIDParams) (SsoIdentity, error) {
	row := q.db.QueryRow(ctx, getSSOIdentityByUserID, arg.UserID, arg.WorkspaceID)
	var i SsoIdentity
	err := row.Scan(
		&i.ID, &i.UserID, &i.WorkspaceID, &i.Provider, &i.ExternalID,
		&i.Email, &i.Name, &i.RawAttributes, &i.LastLoginAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

type CreateSSOIdentityParams struct {
	UserID        uuid.UUID       `json:"user_id"`
	WorkspaceID   uuid.UUID       `json:"workspace_id"`
	Provider      string          `json:"provider"`
	ExternalID    string          `json:"external_id"`
	Email         string          `json:"email"`
	Name          pgtype.Text     `json:"name"`
	RawAttributes json.RawMessage `json:"raw_attributes"`
}

const createSSOIdentity = `-- name: CreateSSOIdentity :one
INSERT INTO sso_identities (
    user_id, workspace_id, provider, external_id, email, name, raw_attributes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, user_id, workspace_id, provider, external_id, email, name, raw_attributes, last_login_at, created_at, updated_at
`

func (q *Queries) CreateSSOIdentity(ctx context.Context, arg CreateSSOIdentityParams) (SsoIdentity, error) {
	row := q.db.QueryRow(ctx, createSSOIdentity,
		arg.UserID, arg.WorkspaceID, arg.Provider, arg.ExternalID,
		arg.Email, arg.Name, arg.RawAttributes,
	)
	var i SsoIdentity
	err := row.Scan(
		&i.ID, &i.UserID, &i.WorkspaceID, &i.Provider, &i.ExternalID,
		&i.Email, &i.Name, &i.RawAttributes, &i.LastLoginAt,
		&i.CreatedAt, &i.UpdatedAt,
	)
	return i, err
}

type UpdateSSOIdentityLastLoginParams struct {
	UserID        uuid.UUID       `json:"user_id"`
	WorkspaceID   uuid.UUID       `json:"workspace_id"`
	Email         string          `json:"email"`
	Name          pgtype.Text     `json:"name"`
	RawAttributes json.RawMessage `json:"raw_attributes"`
}

const updateSSOIdentityLastLogin = `-- name: UpdateSSOIdentityLastLogin :exec
UPDATE sso_identities SET
    last_login_at = NOW(),
    email = $3,
    name = $4,
    raw_attributes = $5,
    updated_at = NOW()
WHERE user_id = $1 AND workspace_id = $2
`

func (q *Queries) UpdateSSOIdentityLastLogin(ctx context.Context, arg UpdateSSOIdentityLastLoginParams) error {
	_, err := q.db.Exec(ctx, updateSSOIdentityLastLogin,
		arg.UserID, arg.WorkspaceID, arg.Email, arg.Name, arg.RawAttributes,
	)
	return err
}

const listSSOIdentitiesForWorkspace = `-- name: ListSSOIdentitiesForWorkspace :many
SELECT id, user_id, workspace_id, provider, external_id, email, name, raw_attributes, last_login_at, created_at, updated_at FROM sso_identities WHERE workspace_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListSSOIdentitiesForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]SsoIdentity, error) {
	rows, err := q.db.Query(ctx, listSSOIdentitiesForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SsoIdentity{}
	for rows.Next() {
		var i SsoIdentity
		if err := rows.Scan(
			&i.ID, &i.UserID, &i.WorkspaceID, &i.Provider, &i.ExternalID,
			&i.Email, &i.Name, &i.RawAttributes, &i.LastLoginAt,
			&i.CreatedAt, &i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const deleteSSOIdentity = `-- name: DeleteSSOIdentity :exec
DELETE FROM sso_identities WHERE id = $1
`

func (q *Queries) DeleteSSOIdentity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSSOIdentity, id)
	return err
}
