// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: webhooks.sql

package sqlc

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createWebhook = `-- name: CreateWebhook :one
INSERT INTO webhooks (workspace_id, url, secret, events, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, workspace_id, url, secret, events, is_active, failure_count, last_triggered_at, last_success_at, created_at, updated_at
`

type CreateWebhookParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Url         string    `json:"url"`
	Secret      string    `json:"secret"`
	Events      []string  `json:"events"`
	IsActive    bool      `json:"is_active"`
}

func (q *Queries) CreateWebhook(ctx context.Context, arg CreateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, createWebhook,
		arg.WorkspaceID,
		arg.Url,
		arg.Secret,
		arg.Events,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.FailureCount,
		&i.LastTriggeredAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWebhookByID = `-- name: GetWebhookByID :one
SELECT id, workspace_id, url, secret, events, is_active, failure_count, last_triggered_at, last_success_at, created_at, updated_at FROM webhooks
WHERE id = $1
`

func (q *Queries) GetWebhookByID(ctx context.Context, id uuid.UUID) (Webhook, error) {
	row := q.db.QueryRow(ctx, getWebhookByID, id)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.FailureCount,
		&i.LastTriggeredAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWebhooksForWorkspace = `-- name: ListWebhooksForWorkspace :many
SELECT id, workspace_id, url, secret, events, is_active, failure_count, last_triggered_at, last_success_at, created_at, updated_at FROM webhooks
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListWebhooksForWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, listWebhooksForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.FailureCount,
			&i.LastTriggeredAt,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWebhook = `-- name: UpdateWebhook :one
UPDATE webhooks
SET url = COALESCE($2, url),
    events = COALESCE($3, events),
    is_active = COALESCE($4, is_active),
    updated_at = NOW()
WHERE id = $1
RETURNING id, workspace_id, url, secret, events, is_active, failure_count, last_triggered_at, last_success_at, created_at, updated_at
`

type UpdateWebhookParams struct {
	ID       uuid.UUID   `json:"id"`
	Url      pgtype.Text `json:"url"`
	Events   []string    `json:"events"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateWebhook(ctx context.Context, arg UpdateWebhookParams) (Webhook, error) {
	row := q.db.QueryRow(ctx, updateWebhook,
		arg.ID,
		arg.Url,
		arg.Events,
		arg.IsActive,
	)
	var i Webhook
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Url,
		&i.Secret,
		&i.Events,
		&i.IsActive,
		&i.FailureCount,
		&i.LastTriggeredAt,
		&i.LastSuccessAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWebhook = `-- name: DeleteWebhook :exec
DELETE FROM webhooks
WHERE id = $1
`

func (q *Queries) DeleteWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWebhook, id)
	return err
}

const getActiveWebhooksForEvent = `-- name: GetActiveWebhooksForEvent :many
SELECT id, workspace_id, url, secret, events, is_active, failure_count, last_triggered_at, last_success_at, created_at, updated_at FROM webhooks
WHERE workspace_id = $1
  AND is_active = TRUE
  AND $2::text = ANY(events)
`

type GetActiveWebhooksForEventParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Event       string    `json:"event"`
}

func (q *Queries) GetActiveWebhooksForEvent(ctx context.Context, arg GetActiveWebhooksForEventParams) ([]Webhook, error) {
	rows, err := q.db.Query(ctx, getActiveWebhooksForEvent, arg.WorkspaceID, arg.Event)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Webhook{}
	for rows.Next() {
		var i Webhook
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Url,
			&i.Secret,
			&i.Events,
			&i.IsActive,
			&i.FailureCount,
			&i.LastTriggeredAt,
			&i.LastSuccessAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementWebhookFailureCount = `-- name: IncrementWebhookFailureCount :exec
UPDATE webhooks
SET failure_count = failure_count + 1
WHERE id = $1
`

func (q *Queries) IncrementWebhookFailureCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementWebhookFailureCount, id)
	return err
}

const resetWebhookFailureCount = `-- name: ResetWebhookFailureCount :exec
UPDATE webhooks
SET failure_count = 0
WHERE id = $1
`

func (q *Queries) ResetWebhookFailureCount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetWebhookFailureCount, id)
	return err
}

const updateWebhookLastTriggered = `-- name: UpdateWebhookLastTriggered :exec
UPDATE webhooks
SET last_triggered_at = NOW(), last_success_at = NOW(), failure_count = 0
WHERE id = $1
`

func (q *Queries) UpdateWebhookLastTriggered(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateWebhookLastTriggered, id)
	return err
}

const disableWebhook = `-- name: DisableWebhook :exec
UPDATE webhooks
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableWebhook(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableWebhook, id)
	return err
}

const createWebhookDelivery = `-- name: CreateWebhookDelivery :one
INSERT INTO webhook_deliveries (webhook_id, event, payload, max_attempts)
VALUES ($1, $2, $3, $4)
RETURNING id, webhook_id, event, payload, response_status, response_body, attempts, max_attempts, last_attempt_at, completed_at, created_at
`

type CreateWebhookDeliveryParams struct {
	WebhookID   uuid.UUID       `json:"webhook_id"`
	Event       string          `json:"event"`
	Payload     json.RawMessage `json:"payload"`
	MaxAttempts int32           `json:"max_attempts"`
}

func (q *Queries) CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, createWebhookDelivery,
		arg.WebhookID,
		arg.Event,
		arg.Payload,
		arg.MaxAttempts,
	)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getWebhookDeliveryByID = `-- name: GetWebhookDeliveryByID :one
SELECT id, webhook_id, event, payload, response_status, response_body, attempts, max_attempts, last_attempt_at, completed_at, created_at FROM webhook_deliveries
WHERE id = $1
`

func (q *Queries) GetWebhookDeliveryByID(ctx context.Context, id uuid.UUID) (WebhookDelivery, error) {
	row := q.db.QueryRow(ctx, getWebhookDeliveryByID, id)
	var i WebhookDelivery
	err := row.Scan(
		&i.ID,
		&i.WebhookID,
		&i.Event,
		&i.Payload,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LastAttemptAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listWebhookDeliveries = `-- name: ListWebhookDeliveries :many
SELECT id, webhook_id, event, payload, response_status, response_body, attempts, max_attempts, last_attempt_at, completed_at, created_at FROM webhook_deliveries
WHERE webhook_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListWebhookDeliveriesParams struct {
	WebhookID uuid.UUID `json:"webhook_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, listWebhookDeliveries, arg.WebhookID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countWebhookDeliveries = `-- name: CountWebhookDeliveries :one
SELECT COUNT(*) FROM webhook_deliveries
WHERE webhook_id = $1
`

func (q *Queries) CountWebhookDeliveries(ctx context.Context, webhookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countWebhookDeliveries, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateWebhookDelivery = `-- name: UpdateWebhookDelivery :exec
UPDATE webhook_deliveries
SET response_status = $2,
    response_body = $3,
    attempts = $4,
    last_attempt_at = NOW(),
    completed_at = $5
WHERE id = $1
`

type UpdateWebhookDeliveryParams struct {
	ID             uuid.UUID          `json:"id"`
	ResponseStatus pgtype.Int4        `json:"response_status"`
	ResponseBody   pgtype.Text        `json:"response_body"`
	Attempts       int32              `json:"attempts"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateWebhookDelivery(ctx context.Context, arg UpdateWebhookDeliveryParams) error {
	_, err := q.db.Exec(ctx, updateWebhookDelivery,
		arg.ID,
		arg.ResponseStatus,
		arg.ResponseBody,
		arg.Attempts,
		arg.CompletedAt,
	)
	return err
}

const getPendingWebhookDeliveries = `-- name: GetPendingWebhookDeliveries :many
SELECT id, webhook_id, event, payload, response_status, response_body, attempts, max_attempts, last_attempt_at, completed_at, created_at FROM webhook_deliveries
WHERE completed_at IS NULL
  AND attempts < max_attempts
  AND (last_attempt_at IS NULL OR last_attempt_at < NOW() - INTERVAL '30 seconds')
ORDER BY created_at ASC
LIMIT 50
`

func (q *Queries) GetPendingWebhookDeliveries(ctx context.Context) ([]WebhookDelivery, error) {
	rows, err := q.db.Query(ctx, getPendingWebhookDeliveries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WebhookDelivery{}
	for rows.Next() {
		var i WebhookDelivery
		if err := rows.Scan(
			&i.ID,
			&i.WebhookID,
			&i.Event,
			&i.Payload,
			&i.ResponseStatus,
			&i.ResponseBody,
			&i.Attempts,
			&i.MaxAttempts,
			&i.LastAttemptAt,
			&i.CompletedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecentWebhookFailures = `-- name: CountRecentWebhookFailures :one
SELECT COUNT(*) FROM webhook_deliveries
WHERE webhook_id = $1
  AND created_at > NOW() - INTERVAL '24 hours'
  AND completed_at IS NOT NULL
  AND (response_status IS NULL OR response_status >= 400)
`

func (q *Queries) CountRecentWebhookFailures(ctx context.Context, webhookID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentWebhookFailures, webhookID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
