// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workspace_branding.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteWorkspaceBranding = `-- name: DeleteWorkspaceBranding :exec
DELETE FROM workspace_branding WHERE workspace_id = $1
`

func (q *Queries) DeleteWorkspaceBranding(ctx context.Context, workspaceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceBranding, workspaceID)
	return err
}

const getWorkspaceBranding = `-- name: GetWorkspaceBranding :one
SELECT id, workspace_id, logo_url, logo_dark_url, favicon_url, primary_color, secondary_color, accent_color, custom_css, hide_powered_by, custom_footer_text, custom_footer_url, created_at, updated_at FROM workspace_branding WHERE workspace_id = $1
`

func (q *Queries) GetWorkspaceBranding(ctx context.Context, workspaceID uuid.UUID) (WorkspaceBranding, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBranding, workspaceID)
	var i WorkspaceBranding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LogoUrl,
		&i.LogoDarkUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.CustomCss,
		&i.HidePoweredBy,
		&i.CustomFooterText,
		&i.CustomFooterUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type UpsertWorkspaceBrandingParams struct {
	WorkspaceID      uuid.UUID   `json:"workspace_id"`
	LogoUrl          pgtype.Text `json:"logo_url"`
	LogoDarkUrl      pgtype.Text `json:"logo_dark_url"`
	FaviconUrl       pgtype.Text `json:"favicon_url"`
	PrimaryColor     pgtype.Text `json:"primary_color"`
	SecondaryColor   pgtype.Text `json:"secondary_color"`
	AccentColor      pgtype.Text `json:"accent_color"`
	CustomCss        pgtype.Text `json:"custom_css"`
	HidePoweredBy    bool        `json:"hide_powered_by"`
	CustomFooterText pgtype.Text `json:"custom_footer_text"`
	CustomFooterUrl  pgtype.Text `json:"custom_footer_url"`
}

const upsertWorkspaceBranding = `-- name: UpsertWorkspaceBranding :one
INSERT INTO workspace_branding (
    workspace_id,
    logo_url,
    logo_dark_url,
    favicon_url,
    primary_color,
    secondary_color,
    accent_color,
    custom_css,
    hide_powered_by,
    custom_footer_text,
    custom_footer_url
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (workspace_id) DO UPDATE SET
    logo_url = EXCLUDED.logo_url,
    logo_dark_url = EXCLUDED.logo_dark_url,
    favicon_url = EXCLUDED.favicon_url,
    primary_color = EXCLUDED.primary_color,
    secondary_color = EXCLUDED.secondary_color,
    accent_color = EXCLUDED.accent_color,
    custom_css = EXCLUDED.custom_css,
    hide_powered_by = EXCLUDED.hide_powered_by,
    custom_footer_text = EXCLUDED.custom_footer_text,
    custom_footer_url = EXCLUDED.custom_footer_url,
    updated_at = NOW()
RETURNING id, workspace_id, logo_url, logo_dark_url, favicon_url, primary_color, secondary_color, accent_color, custom_css, hide_powered_by, custom_footer_text, custom_footer_url, created_at, updated_at
`

func (q *Queries) UpsertWorkspaceBranding(ctx context.Context, arg UpsertWorkspaceBrandingParams) (WorkspaceBranding, error) {
	row := q.db.QueryRow(ctx, upsertWorkspaceBranding,
		arg.WorkspaceID,
		arg.LogoUrl,
		arg.LogoDarkUrl,
		arg.FaviconUrl,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.AccentColor,
		arg.CustomCss,
		arg.HidePoweredBy,
		arg.CustomFooterText,
		arg.CustomFooterUrl,
	)
	var i WorkspaceBranding
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LogoUrl,
		&i.LogoDarkUrl,
		&i.FaviconUrl,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.AccentColor,
		&i.CustomCss,
		&i.HidePoweredBy,
		&i.CustomFooterText,
		&i.CustomFooterUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
