ALTER TABLE qr_codes
    ADD COLUMN dot_style VARCHAR(20) NOT NULL DEFAULT 'square',
    ADD COLUMN corner_style VARCHAR(20) NOT NULL DEFAULT 'square',
    ADD COLUMN size INTEGER NOT NULL DEFAULT 512,
    ADD COLUMN margin INTEGER NOT NULL DEFAULT 4;
