BEGIN;

DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS password_resets;
DROP TABLE IF EXISTS sessions;
DROP TABLE IF EXISTS webhook_deliveries;
DROP TABLE IF EXISTS webhooks;
DROP TABLE IF EXISTS api_keys;
DROP TABLE IF EXISTS bio_page_links;
DROP TABLE IF EXISTS bio_pages;
DROP TABLE IF EXISTS qr_codes;
DROP TABLE IF EXISTS clicks;
DROP TABLE IF EXISTS link_tags;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS link_rules;
DROP TABLE IF EXISTS links;
DROP TABLE IF EXISTS domains;
DROP TABLE IF EXISTS workspace_members;
DROP TABLE IF EXISTS workspaces;
DROP TABLE IF EXISTS users;

DROP EXTENSION IF EXISTS "pgcrypto";

COMMIT;
